# Generated by Django 5.2.8 on 2025-12-01 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.PositiveIntegerField(help_text='Number of correct answers in the game session', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_questions', models.PositiveIntegerField(blank=True, help_text='Optional total questions in the game (useful to compute percentage)', null=True)),
                ('time_taken', models.FloatField(help_text='Time taken to complete the game session in seconds', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('timed', 'Timed')], default='practice', help_text='Indidcates whether the game was played in practice or timed mode', max_length=10)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Optional link to the player (nullable to allow anonymous plays)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Result',
                'verbose_name_plural': 'Game Results',
                'ordering': ['-played_at'],
            },
        ),
    ]
