# Generated by Django 5.2.8 on 2025-12-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='categories_list',
            field=models.JSONField(blank=True, default=list, help_text='List of category IDs played in the game session'),
        ),
    ]
