# Generated by Django 5.2.8 on 2025-12-04 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gameresult_categories_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_to_total_ratio', models.FloatField(default=0.0, help_text='Ratio of correct answers to total questions answered by the player')),
                ('time_taken', models.FloatField(default=0.0, help_text='Total time taken across all games played by the player in seconds')),
                ('user', models.ForeignKey(blank=True, help_text='Optional link to the player (nullable to allow anonymous plays)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadrboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['-correct_to_total_ratio', 'time_taken'],
            },
        ),
    ]
