# Generated by Django 5.2.8 on 2025-12-06 23:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_leaderboardentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='player_name',
            field=models.CharField(blank=True, help_text='Optional player name for anonymous users', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='time_taken',
            field=models.FloatField(help_text='Total time taken across all games played by the player in seconds', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional link to the player (nullable to allow anonymous plays)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
