# Generated by Django 5.2.8 on 2025-12-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gameresult_player_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name the player entered on the leaderboard', max_length=50, null=True),
        ),
    ]
