# Generated by Django 5.2.8 on 2025-12-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_leaderboardentry_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
