# Generated by Django 5.2.8 on 2025-12-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_leaderboardentry_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='display_name',
        ),
    ]
